config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'public_recipes/index'
  get 'shopping_lists/index'

  resources :users do
    resources :foods
    resources :recipes
  end

  resources :recipes do
    resources :recipe_foods
  end

  resources :foods do
    resources :recipe_foods
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/public_recipes/index', to: 'public_recipes#index', as: :public_recipes
  get '/shopping_lists/index', to: 'shopping_lists#index', as: :shopping_lists


  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = RecipeFood.where(recipe_id: params[:id]).includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path(@recipe), notice: 'Your new recipe has been created successfully!'
    else
      redirect_to new_recipe_path, notice: 'An error occured. Please try again.'
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe.update(public: !@recipe.public)
    redirect_to recipe_path(@recipe.id), notice: 'Recipe status updated!'
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!
    redirect_to recipes_path, notice: 'Recipe has been deleted successfully!'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div>
<div>

<p style="color: green"><%= notice %>
</p>

<div class="container-fluid">
  <% if @recipes.length !=0 %>
    <h3 class="text-center">My Recipies</h3>
    <div class="text-center mb-3">
    <%= link_to "Add new recipe", new_recipe_path %>
    </div>

    <% @recipes.each do |recipe| %>
      <div class="container-fluid d-flex card-body">
        <div class="flex flex-row align-items-center mb-4 border border-4">
          <h4 class="card-title"><%= recipe.name %></h4>
          <p class="card-text"><%= recipe.description %></p>
        
        <p>
        <%= link_to "Recipe Details", recipe_path(recipe.id) %>

          <% if can? :destroy, recipe %>
            <%= button_to "Remove", recipe_path(recipe.id), method: :delete %>
          <% end %>
        </p>
        </div>
      </div>
    <% end %>

  <% else %>
    <h1>No recipes available</h1>
    <%= link_to "Add new recipe", new_recipe_path %>
  <% end %>
</div>

</div>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<div>
  <h1>Create a new recipe</h1>
  <%= form_with model: @recipe, url: "/recipes" do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.text_field :name, placeholder: 'Name of Recipe' %>
    <%= f.text_field :preparation_time, placeholder: 'Preparation Time' %>
    <%= f.text_field :cooking_time, placeholder: 'Cooking Time' %>
    <%= f.text_area :description, placeholder: 'Description' %>
    <div>
      <%= f.label :public, "Public" %>
      <%= f.check_box :public %>
    </div>
    <%= f.submit "Create recipe" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<h2>Name: <%= @recipe.name %></h3>
<p>Preparation Time: <%= @recipe.preparation_time %></p>
<p>Cooking Time: <%= @recipe.cooking_time %></p>
<p>Description: <%= @recipe.description %></p>

<div>
  <%= link_to "Generate Shopping List", shopping_lists_path %>
  <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe.id) %>
</div>

<div>
<% @ingredients.each do |ingredient| %>
  
  <p>Name: <%= ingredient.food.name %></p>
  <p>Quantity: <%= ingredient.quantity %></p>
  <p>Price: <%= ingredient.food.price %></p>
  <p>Amount: <%= ingredient.food.price.to_i * ingredient.quantity.to_i %></p>

  <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id) %>
  <%= button_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete %>

  <hr>
<% end %>
</div>