config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'public_recipes/index'
  get 'shopping_lists/index'

  resources :users do
    resources :foods
    resources :recipes
  end

  resources :recipes do
    resources :recipe_foods
  end

  resources :foods do
    resources :recipe_foods
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/public_recipes/index', to: 'public_recipes#index', as: :public_recipes
  get '/shopping_lists/index', to: 'shopping_lists#index', as: :shopping_lists


  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  # before_action :set_recipe_food, only: %i[show edit update destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food.recipe_id = @recipe.id

    if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient has been added successfully!'
    else
      flash[:alert] = 'Failed creating ingredient'
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    recipe_food = RecipeFood.find(params[:id])

    if recipe_food.update(recipe_food_params)
      redirect_to recipe_path(recipe_food.recipe_id), notice: 'Ingredient has been edited successfully!'
    else
      redirect_to recipe_path(recipe_food.recipe_id), alert: 'An error occurred. Please try again.'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy!
    redirect_to recipe_path(@recipe_food.recipe.id), notice: 'Recipe has been deleted successfully!'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_recipe_food
  #   @recipe_food = RecipeFood.find(params[:id])
  # end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<h1>Edit Ingredient</h1>

<div>
  <%= form_with model: @recipe_food, url: recipe_recipe_food_path(recipe_id: @recipe_food.recipe_id, id: @recipe_food.id), method: :put do |f| %>

    <%= f.hidden_field :id, value: @recipe_food.id %>
    <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>
    <br>
    <p>Select Ingredient</p>
    <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class:'form-select'} %>

    <br>
    <p>Quantity</p>
    <%= f.number_field :quantity, { class:'form-select'} %>

    <%= f.submit "Add Ingredient" %>
  <% end %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h4 class="text-center mb-5">Recipe foods</h4>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>
<div>
<%= link_to "New recipe food", new_recipe_food_path %>
</div>

app/views/recipe_foods/new.html.erb
<h1>Add Ingredient</h1>

<div>
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path do |f| %>

    <br>
    <p>Select Ingredient</p>
    <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class:'form-select'} %>

    <br>
    <p>Quantity</p>
    <%= f.number_field :quantity, { class:'form-select'} %>

    <%= f.submit "Add Ingredient" %>
  <% end %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>