config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'public_recipes/index'
  get 'shopping_lists/index'

  resources :users do
    resources :foods
    resources :recipes
  end

  resources :recipes do
    resources :recipe_foods
  end

  resources :foods do
    resources :recipe_foods
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/public_recipes/index', to: 'public_recipes#index', as: :public_recipes
  get '/shopping_lists/index', to: 'shopping_lists#index', as: :shopping_lists


  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">RecipeLand</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
          <li class="nav-item nav">
            <%= link_to "Public Recipes", public_recipes_path, class:"nav-link" %>
            <%= link_to "Food", foods_path, class:"nav-link" %>
            <%= link_to "My Recipes", recipes_path, class:"nav-link" %>
            <%= link_to "Shopping List", shopping_lists_index_path, class:"nav-link" %>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class:"nav-link border-0 bg-light" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div>
    <%= render partial: "layouts/navbar" %>
    <% if notice %>
    <p class="alert alert-success px-10 py-2 bg-green-300"><%= notice %></p>
    <% end %>

    <% if alert %>
    <p class="alert alert-danger px-10 py-2 bg-green-300"><%= alert %></p>
    <% end %>
  </div>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>